version: '3.8'

services:
  web:
    build: .
    container_name: lamp-web
    volumes:
      - ./html:/var/www/html
      - ./certs:/etc/letsencrypt/live
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: userpassword
  
  certbot:
    image: certbot/certbot
    container_name: lamp-certbot
    volumes:
      - ./certs:/etc/letsencrypt/live
      - ./certbot-etc:/etc/letsencrypt
      - ./html:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/html --quiet; done'"

  db:
    image: mysql:8.0
    container_name: lamp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data:
